# Connect to nodes as root user.
ansible_ssh_user: root

# Debug level for all OpenShift components (Defaults to 2)
debug_level: 2

# Set master debug level to 4 to record logins.
openshift_master_debug_level: 2

# Set deployment type to deploy enterprise as opposed to origin or a stand-alone registry
openshift_deployment_type: openshift-enterprise

# Deploy OpenShift 3.11
openshift_release: 3.11

# Specific version of openshift software. Used in pull docker images in tasks/docker-conf.yml
openshift_pkg_version: -3.11.88

#
# This enables all the system containers except for docker:
openshift_use_system_containers: true

#
# Containerized OpenShift Container Platform services are run on all target 
# master and node hosts in the cluster instead.
# If set to false or unset, the default RPM method is used.
containerized: false

#
# Install OpenShift examples by default
openshift_install_examples: true

#
# By default pods run on appnodes
osm_default_node_selector: 'node-role.kubernetes.io/compute=true'

#
# DNSMASQ is Mandatory in OCP >= 3.6
openshift_use_dnsmasq: true

#
# FIREWALLD is now de-facto instead of iptables
os_firewall_use_firewalld: true

# Enable cockpit
osm_use_cockpit: false

# Set cockpit plugins
#osm_cockpit_plugins: ['cockpit-kubernetes']

#
# Disable OpenShift checks
openshift_disable_check: disk_availability,package_availability,package_version,package_update,memory_availability,docker_image_availability,docker_storage
#
