# This variable specifies the size of the per host subnet allocated for pod
# IPs by OpenShift Container Platform SDN. Defaults to 9 which means that
# a subnet of size /23 is allocated to each host; for example, given the
# default 10.128.0.0/16 cluster network, this will allocate 10.128.0.0/23,
# 10.128.2.0/23, 10.128.4.0/23, and so on. This cannot be re-configured
# after deployment.
osm_host_subnet_length: 9

#
# Configure SDN MTU size. This value must be 50 less than the transport MTU for
# SDN overhead and another 62 less for IPSec overhead.
openshift_node_sdn_mtu: 1450

#
# This variable configures which OpenShift Origin SDN plug-in to use for
# the pod network, which defaults to redhat/openshift-ovs-subnet for the
# standard SDN plug-in. Set the variable to redhat/openshift-ovs-multitenant
# to use the multitenant plug-in.
#os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
os_sdn_network_plugin_name: redhat/openshift-ovs-networkpolicy
